import { css } from '@emotion/react';
import Head from 'next/head';
import { useState } from 'react';

export default function RecipeUpload(props) {
  const recipeInstructionsStyles = css`
    width: 800px;
    height: 300px;
  `;

  const [recipeInstructions, setRecipeInstructions] = useState('');
  const [ingredients, setIngredients] = useState([]);
  console.log('ingredients', ingredients);

  const [checked, setChecked] = useState([]);

  // // Add/Remove checked item from list
  // const handleCheck = (event) => {
  //   let updatedList = [...checked];
  //   if (event.target.checked) {
  //     updatedList = [...checked, { id: event.target.value }];
  //   } else {
  //     updatedList.splice(checked.indexOf(event.target.value), 1);
  //   }
  //   setChecked(updatedList);
  //   console.log('updatedList', updatedList);
  // };

  // console.log('checked', checked);

  function handleCheck(index) {
    if (ingredients.includes(index)) {
      const filteredIngredient = ingredients.filter((ingredient) => {
        return ingredient !== index;
      });
      setIngredients(filteredIngredient);
    } else {
      setIngredients([...ingredients, index]);
    }
  }

  console.log('ingredientsOutside', ingredients);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h4>Recipe Name</h4>

          <label>
            Title
            <input />
          </label>
        </div>
        <div>
          <h3>Chose Your Ingredients</h3>

          {props.ingredients.map((ingredient, index) => {
            return (
              <label key={index}>
                {ingredient.name}
                <input
                  value={ingredient.id}
                  type="checkbox"
                  onChange={() => {
                    handleCheck(index + 1);
                    // handleCheck;
                  }}
                />
              </label>
            );
          })}

          <div>
            <h4>Instruction (max. 1000 chars)</h4>
            <input
              css={recipeInstructionsStyles}
              value={recipeInstructions}
              onChange={(event) => {
                setRecipeInstructions(event.currentTarget.value);
              }}
            />
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
