import { css } from '@emotion/react';
import Head from 'next/head';

export default function Home() {
  const homeStyles = css`
    justify-content: center;
    text-align: center;
    margin: 0px auto;
    position: relative;
  `;

  const headlineStyles = css`
    margin-top: 100px;
    color: white;
    margin-top: 100px;
  `;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div css={homeStyles}>
          <div
            style={{
              zIndex: -1,
              position: 'fixed',
              width: '100vw',
              height: '100vh',
            }}
          >
            <img src={'/home2resized.png'} width="100%" height="100%" />
          </div>
          <div css={{ headlineStyles }}>
            <h1>Get new delicious recipes every day</h1>
            <p>Select what you have at home and get surprised</p>
            <button>Hi</button>
          </div>
        </div>
      </main>
    </div>
  );
}
