import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  const homeStyles = css`
    justify-content: center;
    text-align: center;
    padding-top: 100px;
    margin: 100px auto 100px;
    width: 100%;
    height: 100%;
    /* border: 1px solid black; */
    border-radius: 12px;
    position: relative;
  `;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div css={homeStyles}>
          {/* <h1>Home </h1> */}
          {/* <Image src={'/Homepage_resized.jpg'} layout="fill" /> */}
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
